update=14/7/2018 11:14:17
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=ADQ-rescue
LibName2=power
LibName3=device
LibName4=transistors
LibName5=conn
LibName6=linear
LibName7=regul
LibName8=74xx
LibName9=cmos4000
LibName10=adc-dac
LibName11=memory
LibName12=xilinx
LibName13=microcontrollers
LibName14=dsp
LibName15=microchip
LibName16=analog_switches
LibName17=motorola
LibName18=texas
LibName19=intel
LibName20=audio
LibName21=interface
LibName22=digital-audio
LibName23=philips
LibName24=display
LibName25=cypress
LibName26=siliconi
LibName27=opto
LibName28=atmel
LibName29=contrib
LibName30=valves
LibName31=C:/Program Files/KiCad/kicad-library-master/library/ads1115
LibName32=C:/Program Files/KiCad/kicad-library-master/library/mcp6n11
LibName33=C:/Program Files/KiCad/kicad-library-master/library/74xgxx
LibName34=C:/Program Files/KiCad/kicad-library-master/library/74xx
LibName35=C:/Program Files/KiCad/kicad-library-master/library/ac-dc
LibName36=C:/Program Files/KiCad/kicad-library-master/library/actel
LibName37=C:/Program Files/KiCad/kicad-library-master/library/adc-dac
LibName38=C:/Program Files/KiCad/kicad-library-master/library/allegro
LibName39=C:/Program Files/KiCad/kicad-library-master/library/Altera
LibName40=C:/Program Files/KiCad/kicad-library-master/library/analog_devices
LibName41=C:/Program Files/KiCad/kicad-library-master/library/analog_switches
LibName42=C:/Program Files/KiCad/kicad-library-master/library/atmel
LibName43=C:/Program Files/KiCad/kicad-library-master/library/audio
LibName44=C:/Program Files/KiCad/kicad-library-master/library/battery_management
LibName45=C:/Program Files/KiCad/kicad-library-master/library/bbd
LibName46=C:/Program Files/KiCad/kicad-library-master/library/bosch
LibName47=C:/Program Files/KiCad/kicad-library-master/library/brooktre
LibName48=C:/Program Files/KiCad/kicad-library-master/library/cmos_ieee
LibName49=C:/Program Files/KiCad/kicad-library-master/library/cmos4000
LibName50=C:/Program Files/KiCad/kicad-library-master/library/conn
LibName51=C:/Program Files/KiCad/kicad-library-master/library/contrib
LibName52=C:/Program Files/KiCad/kicad-library-master/library/cypress
LibName53=C:/Program Files/KiCad/kicad-library-master/library/dc-dc
LibName54=C:/Program Files/KiCad/kicad-library-master/library/device
LibName55=C:/Program Files/KiCad/kicad-library-master/library/digital-audio
LibName56=C:/Program Files/KiCad/kicad-library-master/library/diode
LibName57=C:/Program Files/KiCad/kicad-library-master/library/display
LibName58=C:/Program Files/KiCad/kicad-library-master/library/dsp
LibName59=C:/Program Files/KiCad/kicad-library-master/library/elec-unifil
LibName60=C:/Program Files/KiCad/kicad-library-master/library/ESD_Protection
LibName61=C:/Program Files/KiCad/kicad-library-master/library/ftdi
LibName62=C:/Program Files/KiCad/kicad-library-master/library/gennum
LibName63=C:/Program Files/KiCad/kicad-library-master/library/graphic
LibName64=C:/Program Files/KiCad/kicad-library-master/library/hc11
LibName65=C:/Program Files/KiCad/kicad-library-master/library/infineon
LibName66=C:/Program Files/KiCad/kicad-library-master/library/intel
LibName67=C:/Program Files/KiCad/kicad-library-master/library/interface
LibName68=C:/Program Files/KiCad/kicad-library-master/library/intersil
LibName69=C:/Program Files/KiCad/kicad-library-master/library/ir
LibName70=C:/Program Files/KiCad/kicad-library-master/library/Lattice
LibName71=C:/Program Files/KiCad/kicad-library-master/library/leds
LibName72=C:/Program Files/KiCad/kicad-library-master/library/LEM
LibName73=C:/Program Files/KiCad/kicad-library-master/library/linear
LibName74=C:/Program Files/KiCad/kicad-library-master/library/logo
LibName75=C:/Program Files/KiCad/kicad-library-master/library/maxim
LibName76=C:/Program Files/KiCad/kicad-library-master/library/MCP2200
LibName77=C:/Program Files/KiCad/kicad-library-master/library/mechanical
LibName78=C:/Program Files/KiCad/kicad-library-master/library/memory
LibName79=C:/Program Files/KiCad/kicad-library-master/library/microchip
LibName80=C:/Program Files/KiCad/kicad-library-master/library/microchip_dspic33dsc
LibName81=C:/Program Files/KiCad/kicad-library-master/library/microchip_pic10mcu
LibName82=C:/Program Files/KiCad/kicad-library-master/library/microchip_pic12mcu
LibName83=C:/Program Files/KiCad/kicad-library-master/library/microchip_pic16mcu
LibName84=C:/Program Files/KiCad/kicad-library-master/library/microchip_pic18mcu
LibName85=C:/Program Files/KiCad/kicad-library-master/library/microchip_pic24mcu
LibName86=C:/Program Files/KiCad/kicad-library-master/library/microchip_pic32mcu
LibName87=C:/Program Files/KiCad/kicad-library-master/library/microcontrollers
LibName88=C:/Program Files/KiCad/kicad-library-master/library/modules
LibName89=C:/Program Files/KiCad/kicad-library-master/library/motor_drivers
LibName90=C:/Program Files/KiCad/kicad-library-master/library/motorola
LibName91=C:/Program Files/KiCad/kicad-library-master/library/motors
LibName92=C:/Program Files/KiCad/kicad-library-master/library/msp430
LibName93=C:/Program Files/KiCad/kicad-library-master/library/nordicsemi
LibName94=C:/Program Files/KiCad/kicad-library-master/library/nxp
LibName95=C:/Program Files/KiCad/kicad-library-master/library/nxp_armmcu
LibName96=C:/Program Files/KiCad/kicad-library-master/library/onsemi
LibName97=C:/Program Files/KiCad/kicad-library-master/library/opto
LibName98=C:/Program Files/KiCad/kicad-library-master/library/Oscillators
LibName99=C:/Program Files/KiCad/kicad-library-master/library/philips
LibName100=C:/Program Files/KiCad/kicad-library-master/library/power
LibName101=C:/Program Files/KiCad/kicad-library-master/library/Power_Management
LibName102=C:/Program Files/KiCad/kicad-library-master/library/powerint
LibName103=C:/Program Files/KiCad/kicad-library-master/library/pspice
LibName104=C:/Program Files/KiCad/kicad-library-master/library/references
LibName105=C:/Program Files/KiCad/kicad-library-master/library/regul
LibName106=C:/Program Files/KiCad/kicad-library-master/library/relays
LibName107=C:/Program Files/KiCad/kicad-library-master/library/rfcom
LibName108=C:/Program Files/KiCad/kicad-library-master/library/RFSolutions
LibName109=C:/Program Files/KiCad/kicad-library-master/library/sensors
LibName110=C:/Program Files/KiCad/kicad-library-master/library/silabs
LibName111=C:/Program Files/KiCad/kicad-library-master/library/siliconi
LibName112=C:/Program Files/KiCad/kicad-library-master/library/stm8
LibName113=C:/Program Files/KiCad/kicad-library-master/library/stm32
LibName114=C:/Program Files/KiCad/kicad-library-master/library/supertex
LibName115=C:/Program Files/KiCad/kicad-library-master/library/switches
LibName116=C:/Program Files/KiCad/kicad-library-master/library/texas
LibName117=C:/Program Files/KiCad/kicad-library-master/library/transf
LibName118=C:/Program Files/KiCad/kicad-library-master/library/transistors
LibName119=C:/Program Files/KiCad/kicad-library-master/library/triac_thyristor
LibName120=C:/Program Files/KiCad/kicad-library-master/library/ttl_ieee
LibName121=C:/Program Files/KiCad/kicad-library-master/library/valves
LibName122=C:/Program Files/KiCad/kicad-library-master/library/video
LibName123=C:/Program Files/KiCad/kicad-library-master/library/wiznet
LibName124=C:/Program Files/KiCad/kicad-library-master/library/Worldsemi
LibName125=C:/Program Files/KiCad/kicad-library-master/library/Xicor
LibName126=C:/Program Files/KiCad/kicad-library-master/library/xilinx
LibName127=C:/Program Files/KiCad/kicad-library-master/library/zetex
LibName128=C:/Program Files/KiCad/kicad-library-master/library/Zilog
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=./
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=Pcbnew
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
